### ISSUE TITLE
Photosensitive epilepsy risk over pet command with high intensity values

### ISSUE THREAD

**Issue by applejuiceyy** [Moonlight-MC/LightLoop#9]
gif output a bit flashy so it's probably commendable to tune the maximum range allowed down
not a lot more to say

**Comment by Manuel-3** [comment]
From a bit of testing I figured 25 seems to be a good max value, its still decently fast but is still smooth and doesn't jitter around.

Fixed in a3635b8870643dac0188b42d4cd643f57b1195d4
